version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mrcut-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=ep-cool-forest-a5q1g1g1.us-east-2.aws.neon.tech
      - POSTGRES_PORT=5432
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=npg_8eruKvscO9dB
      - POSTGRES_DB=neondb
      - DATABASE_URL=postgres://default:npg_8eruKvscO9dB@ep-cool-forest-a5q1g1g1.us-east-2.aws.neon.tech/neondb?sslmode=require
      - DIRECT_URL=postgres://default:npg_8eruKvscO9dB@ep-cool-forest-a5q1g1g1.us-east-2.aws.neon.tech/neondb?sslmode=require
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    depends_on:
      migrations:
        condition: service_completed_successfully
    command: npm run dev

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://default:npg_8eruKvscO9dB@ep-cool-forest-a5q1g1g1.us-east-2.aws.neon.tech/neondb?sslmode=require
      - DIRECT_URL=postgres://default:npg_8eruKvscO9dB@ep-cool-forest-a5q1g1g1.us-east-2.aws.neon.tech/neondb?sslmode=require
    command: npx prisma migrate deploy

volumes:
  postgres_data: 